skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
frost_pass = "8GqPBbxtkA9PbQYmAfb4SrU56tHiYaBh5kPUsHtM2hjk"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
